import type { Citation } from "@/lib/types";
import { Sparkle } from "./icons";

// Render an answer string, turning inline [S#] markers into linked citations.
export function Answer({
  text,
  citations,
  generator,
}: {
  text: string;
  citations: Citation[];
  generator?: string;
}) {
  const byIndex = new Map(citations.map((c) => [c.index, c]));
  const parts = text.split(/(\[S\d+\])/g);

  return (
    <div className="answer">
      <div className="a-label">
        <Sparkle /> Synthesized answer
      </div>
      <div>
        {parts.map((part, i) => {
          const m = part.match(/^\[S(\d+)\]$/);
          if (!m) return <span key={i}>{part}</span>;
          const idx = Number(m[1]);
          const cite = byIndex.get(idx);
          if (!cite?.url) return <span key={i} className="cite">[{idx}]</span>;
          return (
            <a
              key={i}
              className="cite"
              href={cite.url}
              target="_blank"
              rel="noreferrer"
              title={cite.title || cite.url}
            >
              [{idx}]
            </a>
          );
        })}
      </div>
      {generator && generator !== "none" && (
        <div className="gen-note">
          Generated by {generator === "template" ? "the deterministic template" : generator} ·
          every sentence is cited.
        </div>
      )}
    </div>
  );
}
